### ISSUE TITLE
Intensity at limb of star shows emission rather than absorption

### ISSUE THREAD

**Issue by djohn134** [ajwheeler/Korg.jl#245] opened 2023-12-31 16:39 UTC
I noticed the intensities returned at low mu values is in emission rather than absorption. Is this expected? When using SPECTRUM with Kurucz atmospheres the intensities at low mu values still shows absorption. Here is the code I am using to produce this effect:
```using Korg
using PyPlot

lines = Korg.get_VALD_solar_linelist()
A_X = Korg.format_A_X()

Teff = 4500.0
logg = 2.5
# Korg.get_atmosphere_archive()
atmosphere = interpolate_marcs(Teff, logg)

λmin = 6408.5
λmax = 6441.0
Δλ = 0.01
λ = λmin:Δλ:λmax

spectrum = Korg.synthesize(atmosphere, lines, A_X, λmin, λmax, Δλ, air_wavelengths=true)

intensity = spectrum.intensity[3, :]
plot(λ, intensity)
show()
```

**Comment by ajwheeler** [comment] 2024-01-02 16:10
I think this arises from the fact that the Kurucz atmospheres a plane-parallel, while the the MARCS atmospheres are (for low $\log g$) spherical.  At sufficiently low $\mu$, the star is optically thin, so you get emission from lines where the opacity is greater.

There are definitely improvements that could be made to way I'm integrating over $\mu$ (I assume you noticed that the intensity is `0` for the smallest values), but I think this is expected behavior.   (For posterity, I've uploaded the quick notebook I threw together to convince myself that this is what was going on [here](https://gist.github.com/ajwheeler/503f575a1cbb17c1f587ad5e238afdc8).)

Btw, I saw that you've forked Korg and are working on user-specified $\mu$ values (I think?).  Just wanted to say that I'd love to get your upgrades merged in if you are interested, since adding that functionality is on my TODO list. (#191)

**Comment by ajwheeler** [comment] 2024-01-15 17:24
Closing this, but please feel free reply and reopen if you have any Qs or think I may be wrong.

**Closed by ajwheeler** 2024-01-15 17:24 UTC

**Comment by djohn134** [comment] 2024-01-15 17:27
Hey sorry for the late reply! I'd love to merge changes I've made, however my work is only concerned with intensities (for use with my own Doppler imaging code) so I've just haphazerdly added user-defined mu angles with no regard for accurate fluxes down the line.

**Comment by ajwheeler** [comment] 2024-01-15 18:05
No worries!  Hope it works well for you!
